/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-secondary-fixed-variant": "#3f3f46",
              "inverse-primary": "#5b21b6",
              "secondary-fixed": "#a1a1aa",
              "surface-dim": "#0c0c0f",
              "on-tertiary": "#001a12",
              "on-surface-variant": "#a1a1aa",
              "primary-fixed": "#ede9fe",
              "on-error-container": "#fca5a5",
              "on-primary-fixed-variant": "#5b21b6",
              "surface-container-high": "#18181b",
              "on-primary-container": "#ede9fe",
              "outline": "#52525b",
              "surface-container": "#121215",
              "surface": "#0c0c0f",
              "on-background": "#fafafa",
              "outline-variant": "#27272a",
              "error-container": "#3b1111",
              "on-primary-fixed": "#2e1065",
              "tertiary-fixed-dim": "#6ee7b7",
              "on-tertiary-fixed-variant": "#047857",
              "surface-bright": "#18181b",
              "secondary-fixed-dim": "#71717a",
              "inverse-on-surface": "#09090b",
              "on-secondary": "#09090b",
              "surface-container-low": "#0f0f12",
              "surface-container-lowest": "#09090b",
              "background": "#09090b",
              "secondary": "#71717a",
              "error": "#ef4444",
              "tertiary-fixed": "#bbf7d0",
              "tertiary-container": "#065f46",
              "primary-container": "#7c3aed",
              "surface-tint": "#a78bfa",
              "on-secondary-fixed": "#18181b",
              "on-primary": "#0a0012",
              "primary-fixed-dim": "#c4b5fd",
              "on-tertiary-container": "#bbf7d0",
              "inverse-surface": "#fafafa",
              "secondary-container": "#27272a",
              "tertiary": "#34d399",
              "on-secondary-container": "#a1a1aa",
              "on-surface": "#fafafa",
              "on-error": "#1a0000",
              "on-tertiary-fixed": "#003318",
              "primary": "#a78bfa",
              "surface-variant": "#18181b",
              "surface-container-highest": "#1e1e22"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Geist", "sans-serif"],
              "body": ["Geist", "sans-serif"],
              "label": ["Geist", "sans-serif"],
              "geist": ["Geist", "sans-serif"]
      }
    },
  },
  plugins: [],
}
